language: objective-c
osx_image: xcode61

script:
- xctool -project swiftz.xcodeproj -scheme swiftz -sdk macosx ONLY_ACTIVE_ARCH=NO build test
- xctool -project swiftz.xcodeproj -scheme swiftz_ios -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO build test
