env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      before_install:
        - git submodule update --init --recursive
      script:
        - pod lib lint
        - carthage build --no-skip-current
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      before_install:
        - git submodule update --init --recursive
      script:
        - set -o pipefail
        - xcodebuild test -scheme Swiftz | xcpretty -c
        - xcodebuild build-for-testing -scheme Swiftz-iOS -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation)" | xcpretty -c
        - xcodebuild test -scheme Swiftz-iOS -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation)" | xcpretty -c
        - xcodebuild build-for-testing -scheme Swiftz-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p)' | xcpretty -c
        - xcodebuild test -scheme Swiftz-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p)' | xcpretty -c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - git submodule update --init --recursive
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget https://swift.org/builds/swift-5.0-release/ubuntu1404/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-5.0-RELEASE-ubuntu14.04.tar.gz
        - export PATH=${PWD}/swift-5.0-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - swift test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always

